### ISSUE TITLE
Failed to retrieve username for uid=xxxxx

### ISSUE THREAD

**Issue by pozsa** [eth-cscs/sarus#16] opened 2020-10-21 12:25 UTC
Receiving the error mentioned in the subject. I'd welcome any ideas what I might be doing wrong. Thanks.

```bash
-bash-4.2$ sarus --debug images
[6215047.318118181] [<redacted>] [CLI] [DEBUG] parsing CLI arguments of images command
[6215047.318211795] [<redacted>] [CommonUtility] [DEBUG] initializing CLI config's directories for local repository
Failed to retrieve username for uid=<redacted>
See 'sarus help images'
[6215047.345666132] [<redacted>] [main] [ERROR] Error trace (most nested error last):
#0   parseCommandArguments at "CommandImages.hpp":137 Failed to retrieve username for uid=<redacted>
See 'sarus help images'
-bash-4.2$
```

steps taken before trying the above command
```bash
sudo mkdir /opt/sarus
cd /opt/sarus
sudo wget https://github.com/eth-cscs/sarus/releases/download/1.3.0/sarus-Release.tar.gz
tar xf sarus-Release.tar.gz
cd 1.3.0-Release
sudo yum install squashfs-tools
sudo ./configure_installation.sh
export PATH=/opt/sarus/1.3.0-Release/bin:${PATH}
```

extra info:
```bash
File: ‘/opt/sarus/1.3.0-Release/bin/sarus’
Access: (6755/-rwsr-sr-x)  Uid: (    0/    root)   Gid: (    0/    root)
```

**Comment by Madeeks** [comment] 2020-10-21 13:18
Hello @pozsa,
the error is caused by Sarus being unable to find an entry corresponding to the current user in the passwd/group caches created in `<Sarus install path>/etc` (see [here](https://sarus.readthedocs.io/en/stable/install/post-installation.html#automatic-update-of-sarus-passwd-cache) for more information on the passwd/group caches).

The `configure_installation.sh` script, which you are calling as part of your installation steps, should have taken care of creating the caches by using `getent`.

Could you please verify your user is present in Sarus's passwd cache (e.g. `cat /opt/sarus/1.3.0-Release/etc/passwd`)?
Does a call to `getent passwd` return a list of all the users in the system as you would expect them?

**Comment by pozsa** [comment] 2020-10-21 13:57
Hi @Madeeks,
Yes this is going to be the source of the issue.
`getent passwd` does not return all the users in our case.
Hence it's also not in the cache.

Any ideas on how to resolve this? It is not an option on our end for `getent passwd` to return all. The list is way too big.

**Comment by Madeeks** [comment] 2020-10-23 18:24
The most straightforward way you could solve this issue right now is to explicitly add the users (and corresponding groups) which will use Sarus to the passwd/group caches.
Would that be a feasible option?
I'll discuss with the other developers if there are ways we can improve this use case.

**Comment by pozsa** [comment] 2020-10-27 08:33
Thanks. That works for testing our deployment.
I am talking tomorrow to our sys admins managing our HPC cluster. I'll bring up this topic and see if we can make something happen on our end.

**Comment by Madeeks** [comment] 2021-11-15 15:25
Closing due to no further action required on the developer side.
Feel free to reopen with additional details or open a new issue.

**Closed by Madeeks** 2021-11-15 15:25 UTC
